# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Checkstyle and Spotbugs
      run: ./gradlew check
    - name: Jacoco
      run: |
        ./gradlew jacocoTestCoverageVerification
        ./gradlew jacocoTestReport
    - name: run io tests
      run: |
        ./gradlew fatJar
        pip install pytest
        cd $GITHUB_WORKSPACE/
        python -m pytest -v --name build/libs/app-all-1.0.jar --json_file test_data.json test.py
    - name: upload fatjar
      uses: actions/upload-artifact@v1
      with:
        name: fatjar
        path: build/libs/app-all-1.0.jar
    - name: upload reports
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: build/reports/
    - name: webhook test
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: "https://ya.ru"
        data: "{'command': '$GITHUB_WORKSPACE'}"
