# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: PMD Source Code Analyzer Action
      uses: mcanog/setup-pmd@9.2
    - name: run pmd analysis
      run: pmd -d $GITHUB_WORKSPACE/src/main/java -R $GITHUB_WORKSPACE/config/checkstyle/checkstyle.xml -f text
